name: Setup Go
description: Setup Go with module caching

inputs:
  go-version:
    description: Go version to use
    required: true

runs:
  using: composite
  steps:
    - name: 🐹 Set up Go ${{ inputs.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: ⚙️ Download dependencies
      shell: bash
      run: go mod download
